apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: app.py
          image: europe-docker.pkg.dev/concrete-area-334301/rg-light-r/app:v1
          name: app
          ports:
            - containerPort: 8000
      restartPolicy: Always
