apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    db: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      db: db
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        db: db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: rg_light
            - name: POSTGRES_HOST
              value: db
            - name: POSTGRES_PASSWORD
              value: angelita2012
            - name: POSTGRES_USER
              value: santi
          image: postgres:latest
          name: db
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
              subPath: postgres
      restartPolicy: Always
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
status: {}
